" pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on
" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Keybindings
nmap oo o<Esc>
nmap OO O<Esc>
map <Leader>w :update<CR>
map <F2> :set paste<CR>i

" Settings
set expandtab
set relativenumber
set ruler         " show the cursor position all the time
set hlsearch      " highlight matches
set nobackup
set nowritebackup
" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab


" Syntastic Settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
